# -*- coding: utf-8 -*-
"""10_run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sM29STJIVjJM9_tyGP2TwzMsGdYxq-s7
"""

# 別のファイルを引数つきで実行する
#https://flat-kids.net/2021/05/05/googlecolab%E3%81%A7%E5%BC%95%E6%95%B0%E4%BB%98%E3%81%8Dpy%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B/
import os
import glob
from tqdm import tqdm
import geopandas as gpd
import pandas as pd
import rasterio

"""#Generating Points
"""
#1min
os.chdir(r'C:\Users\chihiro\Desktop\GitHub\ReplantingBlueprint')
from _04_Point_generation import _01_generate_points_slope_rev_adjust_6ft

line_shps = glob.glob(r'D:\Malaysia\01_Brueprint\12_Pairing_terraces\5_pairing\_post\_direction\*.shp')
road_shp = r"D:\Malaysia\01_Brueprint\11_Roads\roads_buff_25m.shp" # 2.5 m buffer poly from road line
out_dir = r'D:\Malaysia\01_Brueprint\13_Generate_points\1_allpoints\_rev'
os.makedirs(out_dir, exist_ok=True)

for shp in tqdm(line_shps):
    print(shp)
    _01_generate_points_slope_rev_adjust_6ft.main(shp, road_shp, out_dir)
    

"""# merge all points,
   # delete points within 6ft from Road
   # eliminate close points
 """
# 8 min
os.chdir(r'C:\Users\chihiro\Desktop\GitHub\ReplantingBlueprint')
from _04_Point_generation import _01_mege_and_eliminate_points

in_dir = r"D:\Malaysia\01_Brueprint\13_Generate_points\1_allpoints\_rev"
road_shp =r"D:\Malaysia\01_Brueprint\11_Roads\roads_buff_25m.shp"
#out_dir = in_dir

_01_mege_and_eliminate_points.main(in_dir, road_shp)


"""# extract points for target area
# out_dir is same as input points
"""
# few second
target_area = r"F:\MAlaysia\Blueprint\01_Boundary\target_sloping_area_diss.shp"
point_shp = in_dir + os.sep + "merge_all_points_6ftfin.shp"

gdf_area = gpd.read_file(target_area)
gdf_point = gpd.read_file(point_shp)

points_within_polygon = gpd.sjoin(gdf_point, gdf_area, how='inner', op='within')

out_dir = os.path.dirname(point_shp)
filename = os.path.basename(point_shp)[:-4]+"_target.shp"
outfile = out_dir + os.sep + filename
points_within_polygon.to_file(outfile)


"""# shift 3ft to backslope
"""
# 3 min 30 sec
os.chdir(r'C:\Users\chihiro\Desktop\GitHub\ReplantingBlueprint')
from _04_Point_generation import _02_shift_points

point_shp = outfile
point_shp = r'D:\Malaysia\01_Brueprint\13_Generate_points\1_allpoints\merge_all_points_6ftfin_target.shp'
unet_poly = r"D:\Malaysia\01_Brueprint\09_Terrace_detection\3_dilation\mosaic_e5_d2_clip_arc.shp"
dem_path = r"D:\Malaysia\01_Brueprint\05_R_DEM\DEM_05m_R_kring.tif"
out_dir = r'D:\Malaysia\01_Brueprint\13_Generate_points\02_shift_3ft\_rev'
os.makedirs(out_dir, exist_ok=True)

_02_shift_points.main(point_shp, unet_poly, dem_path, out_dir)













"""# Shift points to 3 ft apart from wall
"""
#4 min
os.chdir(r'C:\Users\chihiro\Desktop\Python\Blueprint\Generate_points\for_local_processing')
import _02_shift_points

point_shp = outfile
# point_shp = r'D:\Malaysia\01_Brueprint\13_Generate_points\01_adjust\merge_allpoints_6ftfin.shp'
unet_poly = r"D:\Malaysia\01_Brueprint\09_Terrace_detection\3_dilation\mosaic_e5_d2_clip_arc.shp"
dem_path = r"D:\Malaysia\01_Brueprint\05_R_DEM\DEM_05m_R_kring.tif"
out_dir = r'D:\Malaysia\01_Brueprint\13_Generate_points\02_shift_3ft'

_02_shift_points.main(point_shp, unet_poly, dem_path, out_dir)


print("All process done")


